name: Deploy to GitHub Pages

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo
  CARGO_TARGET_DIR: ${{ github.workspace }}/target

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6

      - id: remove-package-manager-from-package-json
        name: Remove packageManager attribute from package.json
        run: |-
          sed -i 's/\s"packageManager":\s".*",\n//g' package.json

      - id: use-node-toolchain
        name: Use Node toolchain
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - id: use-rust-toolchain
        name: Use Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - id: make-dot-cargo--directory
        name: Make .cargo directory to store cargo binaries
        run: mkdir -p ./.cargo/bin

      - id: cargo-install-cargo-leptos
        name: Install Cargo-leptos
        run: |-
          curl -L https://github.com/leptos-rs/cargo-leptos/releases/download/v0.3.6/cargo-leptos-x86_64-unknown-linux-gnu.tar.gz \
            | tar xz --strip-components=1 -C ./.cargo/bin &

      - id: cargo-leptos-build-release
        name: Build Leptos WebAssembly
        run: cargo leptos build --release
      
      - id: make-distribution-directory
        name: Create distribution directory
        run: mkdir dist

      - id: hypertext-markup-template
        name: Write HTML template
        run: |-
          cat <<EOF >>dist/index.html
          <!DOCTYPE html>
          <html lang='en'>
            <head>
              <link rel='icon' href='/assets/favicon.ico' />
              <link rel='stylesheet' crossorigin href='/dist/styles.css'>
              <meta charset='UTF-8' />
              <meta name='viewport' content='width=device-width, initial-scale=1.0' />
              <script type='module'>
                import init, { hydrate } from '/pkg/blog.js'
                await init('/pkg/blog.wasm')
                hydrate()
              </script>
            </head>
            <body></body>
          </html>
          EOF

      - id: install-node-dependencies
        name: Install Node dependencies
        run: yarn

      - id: build-stylesheets
        name: Scan code and compile TailwindCSS V4 stylesheet
        run: yarn build

      - id: copy-assets
        name: Copy static files (favicon and et cetera)
        run: |-
          mkdir -p dist/assets
          cp assets/favicon.ico dist/assets/

      - id: copy-blog-posts
        name: Copy markdown files processed by build hook
        run: |-
          mkdir -p dist/posts
          cp -R assets/posts/. dist/posts/

      - id: move-generated
        name: Move generated pkg directory into distribution
        run: mv target/site/pkg dist/pkg

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./dist

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
